config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get "about", to: 'pages#about'
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum:6, maximum: 100}
    validates :description, presence: true, length: {minimum:10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destory ]

    def show
        
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def edit
    
    end

    def create
        @article = Article.new(article_params)
        
        if @article.save
            flash[:notice] = "Artykuł dodano poprawnie!"
            redirect_to @article
        else
            render 'new'
        end
    end

    def update 
    
        if @article.update(article_params)
            flash[:notice] = "Artykuł poprawnie edytowano"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
      
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title,:description) 
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      
    end
  
    def about
  
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h2>Pojawił się problem podczas zapisu artykułu:</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_with(model: @article, local: true) do |f|%>

    <p>
        <%= f.label :tytuł %><br/>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :opis %><br/>
        <%= f.text_area :description %>
    </p>

    <p>
        <%= f.submit :update.capitalize %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edycja artykułu</h1>

<%= render 'form' %>

<%= link_to 'Powrót do strony głównej', articles_path%>

app/views/articles/index.html.erb
<h1>Lista artykułów:</h1>

<table>
    <thead>
        <tr>
            <th>Tytuł</th>
            <th>Opis</th>
            <th colspan="3">Akcja</th>
        
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |art| %>
        <tr>
            <td><%= art.title %></td>
            <td><%= art.description %></td>
            <td><%= link_to 'Show', article_path(art) %></td>
            <td><%= link_to 'Edit', edit_article_path(art) %></td>
            <td><%= link_to 'Delete', article_path(art), method: :delete, data: { confirm: "Jesteś pewien?"} %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<p>
<%= link_to 'Stwórz nowy artykuł', new_article_path%>
</p>

app/views/articles/new.html.erb
<h1>Stwórz nowy artykuł</h1>

<%= render 'form' %>

<%= link_to 'Powrót do listy artykułów', articles_path %>

app/views/articles/show.html.erb
<h1>Showing articles details</h1>

<p><strong>Tytul: </strong> <%= @article.title %> </p> 
<p><strong>Opis: </strong> <%= @article.description %></p>

<%= link_to 'Edycja', edit_article_path(@article) %> |
<%= link_to 'Usuń', article_path(@article), method: :delete, data: { confirm: "Jesteś pewien?"} %> |
<%= link_to 'Powrót', articles_path %>

app/views/layouts/_messages.html.erb
   <% flash.each do |notice, msg|%>
      <%= msg %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages'%>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Tutaj bedzie nowa strona</h1>

<%= link_to 'Lista artykułów', articles_path %> |
<%= link_to 'Strona główna', root_path %>

app/views/pages/home.html.erb
<h1>This is home page</h1>

<%= link_to 'Lista artykułów', articles_path %> |
<%= link_to 'About page', about_path %>